### ISSUE TITLE
Update logo without slogan

### ISSUE THREAD

**Issue by jgwerner** [3Blades/www-site#16]
I believe our main logo within the application should not have the slogan attached to it. Could you update the logo with the blank one? I have attached it.

cc/ @raygesualdo 
<img width="321" alt="logo-horizontal" src="https://cloud.githubusercontent.com/assets/920170/25866055/2075d0e0-34c3-11e7-8b6b-668a57989d27.png">

**Comment by raygesualdo** [comment]
@jgwerner Did you mean the [front-end repo](https://github.com/3Blades/react-frontend)?
